__default__:
    account: jost9358
    partition: short
    job-name: pear_diamond_nico_snake
    mail-type: ALL
    mail-user: jost9358@colorado.edu
    time: 10:00:00 
    nodes: 1
    ntasks-per-node: 20 
    mem: 260gb
    output: /Users/jost9358/Nicotine-Microbiome/run_diamond_out/%j.out
    error: /Users/jost9358/Nicotine-Microbiome/run_diamond_out/%j.err
